### ISSUE TITLE
ROS2対応

### ISSUE THREAD

**Issue by ShotaAk** [SSL-Roots/consai2#59]
CON-SAI2はROS 2にも対応させます。ブランチを切り分けて、ROS1とROS2の両方を残します。

詳細な開発方針はこのissueや、別の方法で議論し、決定します。

**Comment by HansRobo** [comment]
同時にC++化も進めますか？

**Comment by ShotaAk** [comment]
はい。
ROS2バージョンでは、各パッケージの機能をできるだけそのままにして、C++に書き直します。

今のROS1バージョンは、現状のpython(一部C++）で残す予定です。

**Comment by ShotaAk** [comment]
お試しでProjectを立ててみました。
使ったこと無い機能なので、試行錯誤しながらやってみます。

https://github.com/SSL-Roots/consai2/projects/1

**Comment by spiralray** [comment]
PythonからC++へ変更するならdiffを見る必要性がないため、branchではなく別レポジトリにしたほうが良いと思います。

**Comment by ShotaAk** [comment]
> PythonからC++へ変更するならdiffを見る必要性がないため、branchではなく別レポジトリにしたほうが良いと思います。

確かに、中身がほぼほぼ変わるのでそのほうがいいかもしれません。
ありがとうございます。考えてみます。:+1:

**Comment by HansRobo** [comment]
こちら，どうしましょう
ibis内でもAIアーキテクチャ変更に合わせてconsai2のROS2化を進めようと考えているのですが
取り敢えずこちらのリポジトリではpythonベースで移植したらよいですか？

**Comment by HansRobo** [comment]
あと，ROS2対応用のprojectですが権限がないみたいでこちらからは何もできないようになってますね

**Comment by ShotaAk** [comment]
ROS2版のconsai2リポジトリを作りました。
https://github.com/SSL-Roots/consai2r2

このissueはcloseして、consai2r2の方に移動しようかと思います。

Projectページも有ります。
https://github.com/SSL-Roots/consai2r2/projects/1

権限についてですが、issue、pullreqは誰でも出せますが、
projectの編集やマージ作業はRootsメンバーのみになってます。

これは、積極的にContributionしたい場合人にとって面倒になると思うので、
その場合はcollaboratorとして招待しようと思います。（権限関係は設定を調べさせてください）

**Comment by HansRobo** [comment]
TODO : close
